/*
 * This file is generated by jOOQ.
 */
package jooqdata;


import jooqdata.tables.Customer;
import jooqdata.tables.Lot;
import jooqdata.tables.records.CustomerRecord;
import jooqdata.tables.records.LotRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * purchase.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomerRecord> CUSTOMER_PK = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("customer_pk"), new TableField[] { Customer.CUSTOMER.CUSTOMER_CODE }, true);
    public static final UniqueKey<CustomerRecord> CUSTOMER_UNIQUE = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("customer_unique"), new TableField[] { Customer.CUSTOMER.CUSTOMER_CODE_MAIN }, true);
    public static final UniqueKey<LotRecord> LOT_PK = Internal.createUniqueKey(Lot.LOT, DSL.name("lot_pk"), new TableField[] { Lot.LOT.ID }, true);
    public static final UniqueKey<LotRecord> LOT_UNIQUE = Internal.createUniqueKey(Lot.LOT, DSL.name("lot_unique"), new TableField[] { Lot.LOT.CUSTOMER_CODE }, true);
}
